version: '3.8'

services:
  mcp-synaptic:
    image: mcp-synaptic:latest
    container_name: mcp-synaptic-prod
    ports:
      - "8000:8000"
    env_file:
      - ./envs/synaptic.prod.env
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - synaptic-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  redis:
    image: redis:7-alpine
    container_name: mcp-synaptic-redis-prod
    command: redis-server --appendonly yes --appendfsync everysec --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "127.0.0.1:6379:6379"  # Only bind to localhost in production
    volumes:
      - redis-data-prod:/data
    networks:
      - synaptic-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Production monitoring with Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: mcp-synaptic-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - mcp-synaptic
    networks:
      - synaptic-network
    restart: always
    profiles:
      - nginx

volumes:
  redis-data-prod:
    driver: local

networks:
  synaptic-network:
    driver: bridge