version: '3.8'

services:
  mcp-synaptic:
    build: .
    container_name: mcp-synaptic
    ports:
      - "8000:8000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - DEBUG=false
      - LOG_LEVEL=INFO
      - SQLITE_DATABASE_PATH=/app/data/synaptic.db
      - CHROMADB_PERSIST_DIRECTORY=/app/data/chroma
      - REDIS_URL=redis://redis:6379/0
      - REDIS_ENABLED=true
      - DEFAULT_MEMORY_TTL_SECONDS=3600
      - MAX_MEMORY_ENTRIES=10000
      - MEMORY_CLEANUP_INTERVAL_SECONDS=300
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - MAX_RAG_RESULTS=10
      - RAG_SIMILARITY_THRESHOLD=0.7
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - synaptic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: mcp-synaptic-redis
    command: redis-server --appendonly yes --appendfsync everysec
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - synaptic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Redis Web UI for development
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: mcp-synaptic-redis-ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - synaptic-network
    restart: unless-stopped
    profiles:
      - dev

volumes:
  redis-data:
    driver: local

networks:
  synaptic-network:
    driver: bridge