version: '3.8'

services:
  mcp-synaptic:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mcp-synaptic-dev
    ports:
      - "8000:8000"
    env_file:
      - ./envs/synaptic.dev.env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./mcp_synaptic:/app/mcp_synaptic:ro  # Mount source for development
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - synaptic-network
    restart: unless-stopped
    command: ["uv", "run", "mcp-synaptic", "server", "--host", "0.0.0.0", "--port", "8000", "--debug"]

  redis:
    image: redis:7-alpine
    container_name: mcp-synaptic-redis-dev
    command: redis-server --appendonly yes --appendfsync everysec
    ports:
      - "6379:6379"
    volumes:
      - redis-data-dev:/data
    networks:
      - synaptic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: mcp-synaptic-redis-ui-dev
    env_file:
      - ./envs/redis.env
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - synaptic-network
    restart: unless-stopped

volumes:
  redis-data-dev:
    driver: local

networks:
  synaptic-network:
    driver: bridge