services:
  mcp-synaptic:
    build: ..
    container_name: mcp-synaptic
    env_file:
      - ../envs/synaptic.env
    ports:
      - "8000:8000"
    volumes:
      - ../data/synaptic:/app/data
      - ../logs/synaptic:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - synaptic-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1536M
        reservations:
          cpus: '0.25'
          memory: 256M

  redis:
    image: redis:7-alpine
    container_name: mcp-synaptic-redis
    command: redis-server --appendonly yes --appendfsync everysec --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - ./data/redis:/data
    networks:
      - synaptic-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M

  # Optional: Redis Web UI for development
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: mcp-synaptic-redis-ui
    env_file:
      - ./envs/redis.env
    depends_on:
      - redis
    networks:
      - synaptic-network
    restart: unless-stopped
    profiles:
      - dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis-commander.rule=Host(`redis.synaptic.localhost`)"
      - "traefik.http.routers.redis-commander.entrypoints=http"
      - "traefik.http.services.redis-commander.loadbalancer.server.port=8081"
      - "traefik.docker.network=synaptic-network"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 32M


networks:
  synaptic-network:
    driver: bridge